#! /bin/sh

if grep -qv 'kexecd' /proc/cmdline; then
    kexec --load /vmlinuz --initrd=/initrd.img --append=' root=LABEL=DOROOT ro kexecd' &&
    mount -o ro,remount / &&
    kexec -e
fi

exec /etc/init.d/rc S
